apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  namespace: pps6
  annotations:
    cert-manager.io/issuer: "ssl-issuer"
spec:
  tls:
  - hosts:
    - main-front.teaguemm.com
    secretName: tls-main-front
  rules:
  - host: main-front.teaguemm.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-service
            port:
              number: 80
