#This is a comment to cause another push
name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: self-hosted
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker login
        run: docker login ghcr.io -u teaguemurm -p ${{ secrets.GITHUB_TOKEN }}
      - name: Docker build
        run: docker build -t ghcr.io/personal-project-s6/main-front/main-front-image:$GITHUB_SHA -f Dockerfile .;
      - name: Docker publish
        run: docker push ghcr.io/personal-project-s6/main-front/main-front-image:$GITHUB_SHA

#      - name: Setup k8s config
#        run: |
#          mkdir -p /home/ubuntu/.kube
#          echo "${{ secrets.KUBECONFIG }}" >> /home/ubuntu/.kube/config

      - name: Install helm3
        run: sudo snap install helm --classic

      - name: Deploy microservice
        run: helm upgrade main-front-image ./k8s -i -n pps6 --set tag=${{ github.sha }} --kubeconfig '/home/ubuntu/.kube/config'
